### ISSUE TITLE
could c++ exmaples be provided for how to connect broker use paho.mqtt.c

### ISSUE THREAD

**Issue by zyfromsh** [MicrochipTech/gcp-iot-core-examples#12]
phao.mqtt.c uses openssl for security connection, I am struggling with how openssl integerates with ATECC508 chip  where private key is stored  so that paho.mqtt.c could connect broker via openssl

**Comment by bryan-hunt** [comment]
This is question for the paho team. Credentials are provided to OpenSSL via pkcs11 which is loaded as an engine by OpenSSL. This requires application support to pass the correct parameters to OpenSSL.
