### ISSUE TITLE
Python config scripts won't run

### ISSUE THREAD

**Issue by danielepsv** [MicrochipTech/gcp-iot-core-examples#7]
Hello,
I have the ATCRYPTOAUTH_XPRO-B.
I updated the WINC firmware (v19.6.1) with serial bridge (SAMD21 + ATWINC1500 on ext1).
Then I switch the WINC1500 to ATECC608A on ext2 (ext1 is empty -> SAMD21 + ATEC608A on ext2), I build the gcp_iot_core_example and program the SAMD21.
But when I run the script at_config.py I got the error:

**Traceback (most recent call last):
File "at_config.py", line 131, in
configure_device(int(args.i2c,16))
File "at_config.py", line 30, in configure_device
dev.open()
File "D:\IOT_PROJECT\SAMD21\gcp-iot-core-examples-master\scripts\at_kit_base.py", line 41, in open
return self.device.open(vendor_id, product_id)
File "hid.pyx", line 66, in hid.device.open
OSError: open failed**

What's wrong? I'm on windows 10.

Best regards,
Daniele

**Comment by bryan-hunt** [comment]
Did you remove the winc and restart the samd21? The winc has an I2C conflict with the default address of the 608 on the cryptoauth-xpro-b. Once the board has been programmed to work with an alternative i2c address it can be used with the winc.

**Comment by danielepsv** [comment]
Hi Bryan,

I figured it out. It was the DEVICE_HID_VID on at_kit_base.py I switched and it worked. Thanks.

**#DEVICE_HID_VID = 0x04d8
#DEVICE_HID_PID = 0x0f32
DEVICE_HID_VID = 0x03eb
DEVICE_HID_PID = 0x2312**
(This is the correct way)

Best regards,
Daniele
